routes/web.php
<?php

use App\Http\Controllers\ApplicationsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\SessionsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CategoriesController::class, 'index']);

Route::resource('categories', CategoriesController::class)->only('index');
Route::resource('books.applications', ApplicationsController::class)->only(['index', 'create', 'store']);
Route::get('/users/register', [UsersController::class, 'register'])->name('users.register');
Route::post('/users', [UsersController::class, 'store'])->name('users.store');
Route::get('/login', [SessionsController::class, 'create'])->name('sessions.login');
Route::post('/login', [SessionsController::class, 'store'])->name('sessions.store');
Route::delete('/logout', [SessionsController::class, 'destroy'])->name('sessions.delete');

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Application extends Model
{
    use HasFactory;


    /**
     * @var string[]
     */
    protected $fillable = ['return_date', 'user_id', 'book_id'];


    /**
     * @return BelongsTo
     */
    public function book():BelongsTo
    {
        return $this->belongsTo(Book::class);
    }


    /**
     * @return BelongsTo
     */
    public function user():BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ApplicationsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ApplicationRequest;
use App\Models\Application;
use App\Models\Book;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Symfony\Component\HttpFoundation\RedirectResponse;

class ApplicationsController extends Controller
{

    /**
     * @param Book $book
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View
     */
    public function index(Book $book)
    {
        $applications = Application::all();
        return view('applications.index', compact('applications', 'book'));
    }


    /**
     * @param Book $book
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View
     */
    public function create(Book $book)
    {
        if(session()->exists('user_id')) {
            $library_cart = auth_user()->library_cart;
            return view('applications.create', compact('book','library_cart'));
        }
        return view('sessions.create');
    }

    /**
     * @param ApplicationRequest $request
     * @param Book $book
     * @return RedirectResponse
     */
    public function store(ApplicationRequest $request, Book $book):RedirectResponse
    {
        $date = $request->input('return_date');

        if($book->status == 'returned'){
            $book->status = 'expected';
        } else {
            $book->status = 'returned';
        }
        $book->return_date = Carbon::parse($date);
        if($book->return_date <= Carbon::now()) {
            return redirect()->back()->with('error', 'Please enter the correct date!');
        }
        $book->save();

        $application= new Application();
        $application->user_id = auth_user()->id;
        $application->book_id = $book->id;
        $application->return_date = Carbon::parse($date);
        $application->save();
        return redirect()->route('categories.index');
    }
}

resources/views/applications/create.blade.php
@extends('layouts.base')
@section('content')

    <h3>Application form</h3>
    <form enctype="multipart/form-data" method="post" action="{{route('books.applications.store', ['book'=> $book])}}">
        @csrf
        <div class="form-group">
            <label for="library_cart">Library cart</label>
            <input type="text" class="form-control" id="library_cart" name="library_cart" value="{{$library_cart}}"
                   disabled>
        </div>
        <div class="form-group">
            <input type="hidden" class="form-control" id="book_id" name="book_id">
        </div>
        <div class="form-group">
            <label for="author">Book author</label>
            <input type="text" class="form-control" id="author" name="author" value="{{$book->author}}" disabled>
        </div>
        <div class="form-group">
            <label for="denomination">Book denomination</label>
            <input type="text" class="form-control" id="denomination" name="denomination"
                   value="{{$book->denomination}}" disabled>
        </div>
        <div class="form-group">
            <label for="return_date">Return date</label>
            <input type="text" class="form-control border-success  @error('return_date') is-invalid border-danger
                        @enderror" id="return_date" name="return_date">
        </div>
        @error('return_date')
        <p class="text-danger">{{ $message }}</p>
        @enderror
        <button type="submit" class="btn btn-outline-danger">Apply</button>
    </form>
@endsection

resources/views/applications/index.blade.php
@extends('layouts.base')
@section('content')
    @include('notifications.alerts')

    <h2>{{auth_user()->name}}</h2>

    <h3>All applications</h3>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Book denomination</th>
            <th scope="col">Return date</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        @foreach($applications as $application)
            @if(auth_user()->id == $application->user_id)
                <tr>
                    <td>{{$application->book->denomination}}</td>
                    <td>{{date($application->return_date)}}</td>

                    @if($application->book->status == 'returned')
                        <td>{{$application->book->status}}</td>
                    @else
                        @if($application->return_date <= Carbon\Carbon::now())
                            <td>{{$application->book->status}}</td>
                        @else
                            <td>expectedлоллорор</td>
                        @endif
                </tr>
            @endif
            @endif
        @endforeach
        </tbody>
    </table>
@endsection